###############################################################################
#                   Prometheus 2.3.2 Deployment Configuration                 #
###############################################################################
apiVersion: v1
kind: Template
labels:
  app: ${POD_NAME}
  template: deploy-prometheus
message: Deploy Prometheus 2.3.2 Pod is complete
metadata:
  name: deploy-prometheus
  annotations:
    description: Deploy Prometheus 2.3.2 Pod
    iconClass: icon-mysql-database
    openshift.io/display-name: Deploy Prometheus 2.3.2 Pod
    openshift.io/long-description: Deploy Prometheus 2.3.2 Pod
    openshift.io/provider-display-name: ADVLab
    openshift.io/support-url: https://github.com/advlab/prometheus
    tags: advlab
objects:
################################################################################
#                                  Service                                     #
################################################################################
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${POD_NAME}
      template: deploy-prometheus       
    name: ${POD_NAME}
  spec:
    ports:
      - name: 9090-tcp
        port: 9090
        protocol: TCP
        targetPort: 9090
    selector:
      deploymentconfig: ${POD_NAME}
################################################################################
#                                   Route                                      #
################################################################################
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${POD_NAME}
      template: deploy-prometheus 
    name: ${POD_NAME}
  spec:
    port:
      targetPort: 9090-tcp
    to:
      kind: Service
      name: ${POD_NAME}
      weight: 100
    wildcardPolicy: None      
################################################################################
#                              Configuration Map                               #
################################################################################
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: ${POD_NAME}
      template: deploy-prometheus  
    name: ${POD_NAME}
  data:
    prometheus.yml: |
    # Global Properties
    global:
      scrape_interval: 30s
      scrape_timeout: 10s
      evaluation_interval: 30s
    # Alerting Properties  
    alerting:
      alertmanagers:
      - static_configs:
        - targets: []
        scheme: http
        timeout: 10s
    # Scraping Properties
    scrape_configs:
    - job_name: prometheus
      scrape_interval: 10s
      scrape_timeout: 5s
      metrics_path: /actuator/prometheus
      scheme: http
      kubernetes_sd_configs:
      - api_server: null
        role: endpoints
        namespaces:
          names:
            - sandbox
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_label_monitor]
          regex: true
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_app]
          separator: ;
          regex: (.*)
          target_label: app
          replacement: $1
          action: replace
################################################################################
#                         Deployment Configuration                             #
################################################################################
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${POD_NAME}
      template: deploy-prometheus  
    name: ${POD_NAME}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${POD_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: ${POD_NAME}
      spec:
        containers:
          - image: 'prom/prometheus:v2.3.2'
            imagePullPolicy: Always
            name: prometheus
            ports:
              - containerPort: 9090
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /prometheus
                name: prometheus-1
              - mountPath: /etc/prometheus
                name: prometheus-config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - emptyDir: {}
            name: prometheus-1
          - configMap:
              defaultMode: 420
              name: ${POD_NAME}
            name: prometheus-config
    test: false
    triggers:
      - type: ConfigChange
################################################################################
#                            Template Parameters                               #
################################################################################
parameters:
- name: POD_NAME
  description: Pod Name
  displayName: Pod Name
  required: true
- name: NAMESPACE
  description: Monitor Namespace
  displayName: Monitor Namespace
  required: true