global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: erebus
  scrape_interval: 10s
  scrape_timeout: 5s
  metrics_path: /actuator/prometheus
  scheme: http
  kubernetes_sd_configs:
  - api_server: null
    role: endpoints
    namespaces:
      names:
        - sandbox
  relabel_configs:
    - source_labels: [__meta_kubernetes_service_label_monitor]
      regex: true
      action: keep