apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
  name: prometheus
data:
  prometheus.yml: |
    # Global Properties
    global:
      scrape_interval: 30s
      scrape_timeout: 10s
      evaluation_interval: 30s
    alerting:
      alertmanagers:
      - static_configs:
        - targets: []
        scheme: http
        timeout: 10s
    scrape_configs:
    - job_name: prometheus
      scrape_interval: 10s
      scrape_timeout: 5s
      metrics_path: /actuator/prometheus
      scheme: http
      kubernetes_sd_configs:
      - api_server: null
        role: endpoints
        namespaces:
          names:
          - sandbox
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_monitor]
        separator: ;
        regex: "true"
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_pod_label_app]
        separator: ;
        regex: (.*)
        target_label: app
        replacement: $1
        action: replace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
        labels:
          app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.3.2
          ports:
          - containerPort: 9090
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /prometheus
            name: prometheus-1
          - mountPath: /etc/prometheus
            name: prometheus-config
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: prometheus-1
      - configMap:
          defaultMode: 420
          name: prometheus
        name: prometheus-config
# ---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus  
  name: prometheus
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus   